Added inline demo to README
Neovici/cosmoz-moment pull request #2
Opened 2017-07-21 01:05 UTC by dhrytsenko

Notes:

- add webcomponent badge and inline demo
- create description about element for documentation (http://neovici.github.io/cosmoz-moment)

2017-07-21 07:55 UTC, nomego requested changes

2017-07-21 07:55 UTC, nomego commented on README.md
> +    <link rel="import" href="cosmoz-moment.html">
Space indent

2017-07-21 07:55 UTC, nomego commented on README.md
> +	<style is="custom-style">
Is this really needed? wc.org encourages responsive demos

2017-07-21 07:55 UTC, nomego commented on README.md
> +    <div id="container">
container shouldn't be needed

2017-07-21 07:55 UTC, nomego commented on README.md
> +		<paper-listbox class="dropdown-content" slot="dropdown-content" selected="0">
`slot` is for 2.0, we should only add that when we upgrade (and drop `class`)

2017-07-21 07:55 UTC, nomego commented on README.md
> +### Use it inside your element
cosmoz-moment should only be used once per _app_ to manage the locale and moment.js.
cosmoz-moment-timeago can be used within elements, or directly in the app, multiple times.
Another (better?) use case is to implement the Cosmoz.MomentBehavior in an element to be able to compute on `locale` and use moment.js-helpers.

2017-07-21 07:55 UTC, nomego commented on README.md
>  ## Docs
Docs will be handled by wc.org, not sure what their guidelines say about this, maybe omit it?

2017-07-21 07:55 UTC, nomego commented on cosmoz-moment.html
> +Copyright (c) 2015 Neovici AB. All rights reserved.
2017

2017-07-21 07:55 UTC, nomego commented on cosmoz-moment.html
> -			locale = 'en',
indent should not be changed

2017-07-21 07:55 UTC, nomego commented on cosmoz-moment.html
> +				 * @attribute locale
none of these should be needed

2017-07-21 07:55 UTC, nomego commented on cosmoz-moment.html
> +					value: function () {
no need to run a function for String, if you don't, default value will be detectable, too

2017-07-21 07:55 UTC, nomego commented on demo/index.html
> +					<paper-listbox class="dropdown-content" slot="dropdown-content" selected="0">
slot for 2.0, leave it for now, will replace class later

2017-07-21 07:55 UTC, nomego commented on test/cosmoz-moment.html
> +		test('get default locale value', function () {
should probably mention the expected value - "default locale is 'en'" or something

2017-07-21 07:55 UTC, nomego commented on test/cosmoz-moment.html
> +	suite('binding to locale property', function() {
would also be good with a test that sets the locale on cosmoz-moment and then observes a change in a cosmoz-moment-timeago

2017-07-21 07:55 UTC, nomego commented on test/cosmoz-moment.html
> +	<template is="dom-bind" id="custom-locale">
shouldn't this also be in a test-fixture?

2017-07-21 11:54 UTC, dhrytsenko commented on README.md
> +	<style is="custom-style">
l added it for extra space on bottom cause dropdown list will have scrollbar in webcomponents preview. it's not critical and l will remove it

2017-07-21 11:55 UTC, dhrytsenko commented on README.md
> +		<paper-listbox class="dropdown-content" slot="dropdown-content" selected="0">
Yes, it's make sence

2017-07-21 12:32 UTC, dhrytsenko commented on README.md
>  ## Docs
l think we can leave it if we have plans to add more complex examples. This link to docs will show `gh-pages` with property list and some additional examples. `gh-pages` provide live docs and previews of our element via GitHub pages.

2017-07-21 14:42 UTC, dhrytsenko commented on test/cosmoz-moment.html
> +	suite('binding to locale property', function() {
yes, it'll be nice. l added basic tests for cosmoz-moment-timeago and will try to create what you describe

2017-07-22 06:13 UTC, nomego requested changes
All comments from the last review are not addressed still

2017-07-22 06:13 UTC, nomego commented on test/cosmoz-moment-timeago.html
> +            assert.notEqual(timeagoSpan.textContent, 'Invalid date', 'date has invalid value');
spacing indent

2017-07-22 06:13 UTC, nomego commented on test/index.html
> +            'cosmoz-moment-timeago.html',
spacing indent

2017-07-22 06:15 UTC, nomego commented
Also, build is failing.

2017-07-24 07:31 UTC, dhrytsenko commented
There are some issues in Firefox while run tests. l work on it

2017-07-24 13:20 UTC, dhrytsenko commented
@nomego, I fixed travis build issue. Could you check it again, please?

2017-07-25 21:08 UTC, nomego requested changes

2017-07-25 21:08 UTC, nomego commented on cosmoz-moment.html
> -			locale = 'en',
Not addressed

2017-07-25 21:08 UTC, nomego commented on cosmoz-moment.html
>  		var localSharedMoment = moment(),
Does not seem used anymore? Drop in that case

2017-07-25 21:08 UTC, nomego commented on demo/index.html
> +					<paper-listbox class="dropdown-content" slot="dropdown-content" selected="0">
Not addressed (do not add the `slot` attribute)

2017-07-26 06:22 UTC, dhrytsenko commented on cosmoz-moment.html
>  		var localSharedMoment = moment(),
We can't remove it cause use it in `MomentBehavior` to set local moment variable:
 
    `Cosmoz.MomentBehavior = {
         properties: {
		locale: {
			type: String,
			readOnly: true,
			value: function () {
				return locale;
			}
		},
		moment: {
			type: Object,
			value: localSharedMoment
		}
	},`

2017-07-26 06:42 UTC, dhrytsenko commented on cosmoz-moment.html
> -			locale = 'en',
Is it correct indent: 

    `var localSharedMoment = moment(),
     locale = 'en',
     momentElements = [];` 

or you want this:

    `var localSharedMoment = moment(),
		 locale = 'en',
		 momentElements = [];` 

Now we have first indent for variables

2017-07-26 07:30 UTC, nomego commented on cosmoz-moment.html
>  		var localSharedMoment = moment(),
In "Added component and variable description for docs"(bfd23ec8f7b8eaca646ccbb75c920549c66b65a9) that property is removed.

2017-07-26 07:31 UTC, nomego commented on cosmoz-moment.html
> -			locale = 'en',
The last one. It was correct before the PR, see https://github.com/Neovici/cosmoz-moment/pull/2/files

2017-07-26 07:35 UTC, dhrytsenko commented on cosmoz-moment.html
>  		var localSharedMoment = moment(),
it was removed from cosmoz-moment component properties but still exist in behavior properties

2017-07-26 07:58 UTC, nomego commented on cosmoz-moment.html
>  		var localSharedMoment = moment(),
Oh ok, I see.

2017-07-26 07:58 UTC, nomego approved these changes

2017-07-26 07:58 UTC, merged